### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by DavidDoes** [dmtrKovalenko/material-ui-pickers#960] opened 2019-03-22 00:35 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    ^2.2.4     |
| @material-ui/core       |     ^3.9.2    |
| React               |    ^16.2.0     |
| Browser             |    any     |
| @date-io/moment        |    ^1.1.0     | 

## Steps to reproduce
1. `npm i material-ui-pickers --save`
2. `npm i @date-io/moment moment --save`

## Expected behavior
Component installs dependencies

## Actual behavior
Lack of dependencies installed. 

- First, error showing that the Button component from `material-ui` is missing, which is when I realize that the entire `material-ui` dependency is not installed. So, `npm i @material-ui/core --save`
- Now, `Error: ENOENT: no such file or directory, open '/project/node_modules/@material-ui/core/node_modules/deepmerge/dist/umd.js'` 

I'm at a loss here.

**Comment by dmtrKovalenko** [comment] 2019-03-22 14:34
Please make a reproduction at https://codesandbox.io/

**Comment by dmtrKovalenko** [comment] 2019-03-25 19:53
Closing due to missing information

**Closed by dmtrKovalenko** 2019-03-25 19:53 UTC
Labels: 🤷‍♂️ need more information
