### ISSUE TITLE
Broken focus with material-ui@1.0.0-beta.39+

### ISSUE THREAD

**Issue by LastDreamer** [dmtrKovalenko/material-ui-pickers#342] opened 2018-04-09 14:04 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.5     |
| material-ui         |    1.0.0-beta.41     |
| React               |    16.2.0     |
| Browser             |    Chrome/65.0.3325.181     |
| Platform            |    MacOS X     |

## Steps to reproduce
1. Focus DatePicker input
2. Blur DatePicker input

## Expected behavior

Focus should lost after blur

## Actual behavior

Input stay focused after blur

## Live example
https://codesandbox.io/s/535jw62ol4

**Comment by letalumil** [comment] 2018-04-12 15:31
It seems to be the problem of material-ui itself. I can reproduce the behaviour with [Selects](https://material-ui-next.com/demos/selects/).

**Comment by dmtrKovalenko** [comment] 2018-04-14 09:24
Closing as material-ui TextField issue

**Closed by dmtrKovalenko** 2018-04-14 09:24 UTC

**Comment by gustavo-tailrecursive** [comment] 2019-04-02 23:41
this still happening on 

"@material-ui/core": "1.1.0"
"material-ui-pickers": "1.0.0-rc.9"

what is the easiest way to solve this?
@dmtrKovalenko, @LastDreamer  ?
