### ISSUE TITLE
issue selecting other year

### ISSUE THREAD

**Issue by yanv1991** [dmtrKovalenko/material-ui-pickers#63] opened 2017-11-19 15:21 UTC
in the calendar you need to select a year twice to see the right month

**Comment by dmtrKovalenko** [comment] 2017-11-19 17:19
I`m scared but can you add more steps to reproduce

**Comment by arthwood** [comment] 2017-11-23 17:15
@dmtrKovalenko 
1. Click on field - calendar pops up (with current date)
2. Click on year (top-left) corner and change to 2016
3. Year indicator in top-left corner changes to 2016, but in the month navigation (with side arrows) it still says "November 2017" and selecting actual date resolves to date in 2017.

**Comment by dmtrKovalenko** [comment] 2017-11-24 08:19
@arthwood @yanv1991 
I have tried to reproduced that - but its works. Please provide more details about your environment, sandbox or something else to have me an ability to fix that quickly.
Thanks!

**Comment by sakulstra** [comment] 2017-11-28 18:36
@arthwood i had the same problem but now in beta-5 it seems to be gone - can you verify(i also updated material ui, eventually this was somehow related)?

**Comment by arthwood** [comment] 2017-11-28 18:39
Thanks @sakulstra I no longer have access to the project where the issue occured but I believe beta-5 fixes it 😄

**Comment by dmtrKovalenko** [comment] 2017-11-29 08:19
I`m closing this issue. If it`s still reproducible for somebody, please let me know 😄

**Closed by dmtrKovalenko** 2017-11-29 08:19 UTC
