### ISSUE TITLE
minDate for DateTimePicker does not honor time provided

### ISSUE THREAD

**Issue by elliotstoner** [dmtrKovalenko/material-ui-pickers#940] opened 2019-03-04 19:17 UTC
![Time Meme](https://cache.lovethispic.com/uploaded_images/250613-What-Time-Is-It-Thursday.jpg)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.1.1 |
| material-ui         | 3.8.3 |
| React               | 16.4.2 |
| Browser             | Any |
| Peer library        | moment 2.22.2 |

## Steps to reproduce
1. Create two DateTimePickers (start and end date); start date is provided as the "minDate" for the end date (live example below)
2. Click Start Date, select any date/time in the future
3. Click End Date, select the same date as the start date, but select a time earlier than the start time

## Expected behavior
As a **DateTimePicker**, both the date and time should be considered when providing a minimum DateTime (if I didn't care about the time then I would use a DatePicker).

i.e. If I select 2/5/19 4:00:00pm as the start date and 2/5/19 1:00:00pm as the end date, the picker should enter into an error state.

## Actual behavior
The DateTimePicker takes into account previous dates, but not a time that is previous to the selected time.

If I select 2/5/19 4:00:00pm as the start date and 2/5/19 1:00:00pm as the end date, the picker does not enter into an error state.

## Live example
https://codesandbox.io/s/73v5xzxj5x

**Comment by elliotstoner** [comment] 2019-03-04 19:24
I'm sure someone somewhere has a very compelling argument why `minDate` should not account for the time. If there's a fear of backwards compatibility or loss of ease of use (expecting `moment().add(1, 'd')` to allow all times for tomorrow), then I would propose creating a `minDateTime` property that does allow for users to pass a Date (or moment, etc) and expect it to honor the time value that's been passed.

**Comment by dmtrKovalenko** [comment] 2019-03-05 08:51
Duplicate of #519

**Closed by dmtrKovalenko** 2019-03-05 08:51 UTC
