### ISSUE TITLE
DatePicker keyboardIcon

### ISSUE THREAD

**Issue by henrik1234** [dmtrKovalenko/material-ui-pickers#804] opened 2018-12-12 14:39 UTC
This is my first issue report so bear with me
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     2.0.4    |
| material-ui         |    3.6.2     |
| React               |    16.5.2     |
| Browser             |     Google Chrome Version 71.0.3578.80 (64 bit)    |
| Peer library        |   material-ui-icons 3.0.1,  moment 2.22.2      | 

## Steps to reproduce
1. Create DatePicker or TimePicker with disabled prop and keyboardIcon
2. set `<DatePicker disabled={true} keyboardIcon={<Event />} />`
3. Click on keyboardIcon when disabled prop is true

## Expected behavior
Nothing

## Actual behavior
`InputBase.js:308 Uncaught TypeError: _this.inputRef.focus is not a function`

## Live example
https://codesandbox.io/s/w25j5vo7m5

##
Clicking on the keyboardIcon when the datepicker is disabled, the html <button>(the icon) has a style with `pointer-events: none`. If we set the `pointer-events: auto` no error occurs. Perhaps an issue with event bubble?

**Comment by dmtrKovalenko** [comment] 2018-12-21 10:18
Duplicate of https://github.com/dmtrKovalenko/material-ui-pickers/issues/784

**Closed by dmtrKovalenko** 2018-12-21 10:18 UTC

**Comment by NYannick** [comment] 2019-03-26 09:24
Hi @dmtrKovalenko, when i use props keyboardIcon. It doesn't displayed Icon <Event /> for open picker button in keyboard mode :/
