### ISSUE TITLE
DateTimePicker shows day-numers as day of year and not day of month

### ISSUE THREAD

**Issue by ilbrando** [dmtrKovalenko/material-ui-pickers#593] opened 2018-08-23 07:32 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.13       |
| material-ui         |    1.5.1     |
| React               |     16.4.2    |
| Browser             |   Chrome      |
| Platform            |     Windows 10    |
| Peer library        |   date-fns: 2.0.0-alpha.16      | 

## Steps to reproduce
It appears that the Calender component is using format("D") which is documented in [format/index.js](https://github.com/date-fns/date-fns/blob/master/src/format/index.js) to return the daynumber of the year. It should have used format("d"). I think the error is in the getDayText function in [date-fns-utils.js](https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/lib/src/utils/date-fns-utils.js).

## Expected behavior
Number of day of the month, that is 1-31.

## Actual behavior
Number of the day of the year, that is 1-365.

![datetimepickerdayerror](https://user-images.githubusercontent.com/11632690/44511138-d99cf100-a6b6-11e8-954a-839515dd61aa.jpg)

**Comment by dmtrKovalenko** [comment] 2018-08-23 07:32
Duplicate of #414

**Closed by dmtrKovalenko** 2018-08-23 07:32 UTC

**Comment by ilbrando** [comment] 2018-08-23 07:38
Wow, that was quick response, thanks :-)
