### ISSUE TITLE
Calendar is showing day of the year instead of day of month

### ISSUE THREAD

**Issue by JaredDiCioccio** [dmtrKovalenko/material-ui-pickers#582] opened 2018-08-17 21:22 UTC
Basically, I'm seeing dates as day of the year (August 229 instead of August 20th or whatever). I'm not sure if there's a setting I'm just not providing properly. I remember this previously working as expected earlier this week. I don't see any settings that would affect this. 

It doesn't happen in the online examples on the documentation website, so might be a weird local thing.

![mdfzujh](https://user-images.githubusercontent.com/633075/44288832-af26e000-a23f-11e8-88e1-74a7a51915b4.png)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  ^1.0.0-rc.12 |
| material-ui         |  ^1.4.3       |
| React               |  ^16.4.2       |
| Browser             |   Chrome , latest     |
| Platform            |    Win10   |
| Peer library        |   date-fns   ^2.0.0-alpha.7 |

Code using to use DateTimePicker, basically copy/pasted from website.

```
      <MuiPickersUtilsProvider utils={DateFnsUtils}>
        <DateTimePicker
          value={selectedDate}
          onChange={this.handleDateChange}        
        />
      </MuiPickersUtilsProvider>
```

## Steps to reproduce
1. Click on date time picker

## Expected behavior
Should see days of month, 1-31

## Actual behavior
Seeing day of the year, 1-365

**Comment by dmtrKovalenko** [comment] 2018-08-19 11:44
Duplicate of #414

**Closed by dmtrKovalenko** 2018-08-19 11:44 UTC
