### ISSUE TITLE
Wrong display of day of the month in the date picker

### ISSUE THREAD

**Issue by o-m-a-r-k** [dmtrKovalenko/material-ui-pickers#425] opened 2018-05-21 14:26 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.9     |
| material-ui         |    1.0.0     |

## Steps to reproduce
1. include the DatePicker in the page
2. open the picker

## Expected behavior
Display of day of the month

## Actual behavior
Display of day of the year

**Comment by cherniavskii** [comment] 2018-05-21 15:25
Duplicate of #424

**Closed by cherniavskii** 2018-05-21 15:25 UTC
