### ISSUE TITLE
Mindate does not limit time

### ISSUE THREAD

**Issue by AugustoAmaral** [dmtrKovalenko/material-ui-pickers#959] opened 2019-03-22 00:07 UTC
![](https://thumbs.gfycat.com/DifficultDiligentCobra-small.gif)
Hello guys, how are you?

I was using the minDate props on dateTime picker and I noticed that only past dates are limited and not past hours, my solution was use a validation to block submit but it would be awesome if i could disable past hours like dates.

**Comment by JavierLight** [comment] 2019-03-22 09:41
Is any provisional workaround for this? I think this would be a great feature! 👍

**Comment by dhruuuuuv** [comment] 2019-03-22 12:40
seconded! This functionality seems strange... can anyone suggest a fix?

**Comment by dmtrKovalenko** [comment] 2019-03-22 14:35
Duplicate of #519 0

**Closed by dmtrKovalenko** 2019-03-22 14:35 UTC
