### ISSUE TITLE
Keyboard-icon position is a bit off in IE11

### ISSUE THREAD

**Issue by ChristophGr** [dmtrKovalenko/material-ui-pickers#487] opened 2018-06-28 05:43 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |         |
| material-ui         |    1.2.0     |
| React               |     1.0.0-rc.10    |
| Browser             |     IE11    |
| Platform            |     Windows 10    |

## Steps to reproduce
1. 
2.
3.

## Expected behavior
Icon-positions as they are rendered in Firefox or Chrome
<img width="644" alt="datepicker_in_firefox" src="https://user-images.githubusercontent.com/135216/42015259-e4fc59fa-7aa6-11e8-9667-b100abf3862e.png">
## Actual behavior
Icons' positions seem a little too low on the y-axis in IE11 
![datepicker_in_ie11](https://user-images.githubusercontent.com/135216/42015258-e4d6e88c-7aa6-11e8-9009-c29d864734d5.png)

## Live example
It can be observed on the demo-page
https://material-ui-pickers.firebaseapp.com/demo/datepicker

**Comment by dmtrKovalenko** [comment] 2018-06-28 06:11
Duplicate of #222

**Closed by dmtrKovalenko** 2018-06-28 06:11 UTC
