### ISSUE TITLE
Error validation not working with Formik and Yup

### ISSUE THREAD

**Issue by SebSchwartz** [dmtrKovalenko/material-ui-pickers#919] opened 2019-02-12 14:23 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     2.2.1    |
| material-ui         |      3.9.2   |
| React               |   16.8.1     |
| Browser             |   Chrome   71   |
| Peer library        |    date-fns(date-io): 1.1.0      |
| Formik             |  1.5.0   |
| Yup             |  0.26.10   |

## Steps to reproduce
1. A form using formik with an InlineDatePicker and formik configured for Yup schema validation.
2. The shema of validation validates some stuffs on the fields of InlineDatePicker. Here as schema definition for those files:
```
startDate: Yup.date().required(),
  endDate: Yup.date().when('startDate', (startDate, schema) => (startDate ? schema.min(startDate) : schema.date())),
```
3. There is no errors at all that appears. If I remove those two schema validation, it works perfectly.

## Expected behavior
The picker does not block schema validation.

## Actual behavior
Schema validation is no more working for any field on the schema.

**Comment by dmtrKovalenko** [comment] 2019-02-12 19:48
We know that - in v3 (#862) we will definitely recreate for integration process. Possibly duplicate of #836.

**Closed by dmtrKovalenko** 2019-02-12 19:48 UTC

**Comment by dan-turner** [comment] 2019-09-17 00:50
@dmtrKovalenko are you able to please provide an example of how to do this properly now?

**Comment by jdmairs** [comment] 2019-10-09 17:38
I'm also trying to figure out how to use yup with the date-picker.

**Comment by nilamsavani91** [comment] 2019-11-18 15:41
> I'm also trying to figure out how to use yup with the date-picker.

I also want to set the validation if the endDate is less than StartDate. I am using KeyboardDatePicker from material-ui pickers.

**Comment by maxmann74** [comment] 2020-03-04 01:12
I am having this issue as well.  The "Invalid Date" error shows up, but when I clear the value, the "Required" error never shows up.
