### ISSUE TITLE
Provide original DOM event to onChange

### ISSUE THREAD

**Issue by charlax** [dmtrKovalenko/material-ui-pickers#974] opened 2019-04-04 06:48 UTC
**Is your feature request related to a problem? Please describe.**

I want to have some kind of inline edit behavior, where the user can click on a date, which will open a popover containing an autofocused `DateTextField` with keyboard entry and a picker icon. Once the user has finished choosing a date, I would like to close the popover.

![image](https://user-images.githubusercontent.com/120501/55534929-ec988a80-56b5-11e9-801c-77a5788b6547.png)

Context: 

* I can only rely on `onChange` for that.
* `onChange` is fired when a date is selected using the picker **and** when the `TextField` is blurred.

Problem : I would like to autofocus the `TextField` once the popover open. But then, if the user clicks on the picker icon, the `TextField` loses focus and an `onChange` event is emitted.

**Describe the solution you'd like**

If I had the original DOM event as a second argument to `onChange(date, ev)`, I would be able to discriminate between:

* `clickdown`, `keydown` (for enter and escape) which should submit the change
* `blur` which shouldn't.

**Describe alternatives you've considered**

* Only allow keyboard entry? Not ideal.
* Do not autofocus? Not ideal either, and the behavior will happen anyway if the user focuses the textfield before clicking on the picker icon.

**Comment by charlax** [comment] 2019-04-04 07:04
Similar to #948 by the way. Will this be solved by #862?

**Comment by dmtrKovalenko** [comment] 2019-04-06 08:52
Duplicate of #919 and a lot of other issue. We cannot provide original dom event

**Closed** 2019-04-06 08:52 UTC

**Comment by charlax** [comment] 2019-04-13 13:22
Why is not possible? It's by design? Or technically impossible?

**Comment by dmtrKovalenko** [comment] 2019-04-13 13:30
Date can be submitted from several places. Click button. Enter keydown. Blur focus.

**Comment by charlax** [comment] 2019-04-13 13:33
Yes indeed. But why can't the original event be also provided to `onChange`, on top of the value?

`onChange(value, event)`

**Comment by dmtrKovalenko** [comment] 2019-04-13 14:59
No we can’t :) 
This will be not obvious.

**Comment by charlax** [comment] 2019-04-13 15:01
I’m sorry, not obvious?

**Comment by FoxyWolfy** [comment] 2019-11-26 18:37
What's not obvious is where the date came from.  Without the event a complex app doesn't have the originating "event.target" and therefore cannot determine the originating control with "event.target.name".  All we get is a "date".  From which control?  I have multiple modules with dozens of controls that send changes up to a  parent.  This is the only control that doesn't forward the event on an onChange.  The "event.target.value" should contain the "date".

**Comment by oliviertassinari** [comment] 2019-11-26 18:40
+1 for always providing the event as the first argument to any user facing event prop handler.
