### ISSUE TITLE
Getting Error as - TypeError: __WEBPACK_IMPORTED_MODULE_13_clsx___default(...) is not a function. Since installed material-ui-pickers with redux-form

### ISSUE THREAD

**Issue by storesbuzz** [dmtrKovalenko/material-ui-pickers#923] opened 2019-02-18 10:19 UTC

**Comment by dmtrKovalenko** [comment] 2019-02-18 10:30
Duplicate of #894

**Closed** 2019-02-18 10:30 UTC
