### ISSUE TITLE
what the.  .. 

### ISSUE THREAD

**Issue by rchancey** [dmtrKovalenko/material-ui-pickers#920] opened 2019-02-15 01:30 UTC
always a  joy coping  code line for line from demos and have it blow up.

I googled  and nothing... I coped  line  for line from  the material UI docs  and got  this:

any ideas?

TypeError: __WEBPACK_IMPORTED_MODULE_13_clsx___default() is not a function. (In '__WEBPACK_IMPORTED_MODULE_13_clsx___default()(classes.dialogRoot, (_b = {}, _b[classes.dialogRootWider] = wider, _b[classes.dialogWithTabs] = showTabs, _b))', '__WEBPACK_IMPORTED_MODULE_13_clsx___default()' is "/static/media/clsx.e09d1725.mjs")

```
return  <MuiPickersUtilsProvider utils={DateFnsUtils}>
            <Grid container className='grid' justify="space-around">
                <DatePicker
                    margin="normal"
                    label="Date picker"
                    value={selectedDate}
                    onChange={this.handleDateChange}
                />
                <TimePicker
                    margin="normal"
                    label="Time picker"
                    value={selectedDate}
                    onChange={this.handleDateChange}
                />
            </Grid>
        </MuiPickersUtilsProvider>;

import { MuiPickersUtilsProvider, TimePicker, DatePicker } from 'material-ui-pickers';
import DateFnsUtils from '@date-io/date-fns';
```

**Comment by MathiasKandelborg** [comment] 2019-02-15 10:47
Hi, it seems that webpack is trying to import clsx (a small 'classes' library). But something goes terribly wrong. 

I'd suggest to remove and install your node_modules folder. Then make sure `clsx` comes along. 

Besides that, imports should be done at the beginning of a file, before anything else. If there's more error, the very first (sensible) message tends to be the most useful of an error stack (the one at the top).

**Comment by dmtrKovalenko** [comment] 2019-02-15 19:24
Duplicate of #894

**Closed by dmtrKovalenko** 2019-02-15 19:24 UTC
