### ISSUE TITLE
calendar latest version problem 

### ISSUE THREAD

**Issue by vladimirvorobiev** [dmtrKovalenko/material-ui-pickers#872] opened 2019-01-21 14:55 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |        latest |
| material-ui         |         latest|
| React               |         6.16|
| Browser             |         any|
| Peer library        |         | 

## Steps to reproduce
1.
https://material-ui-pickers.firebaseapp.com/localization/persian  
click datepicker
2. Open chrome devtool
3.errors:
TypeError: t.props.utils.startOfMonth is not a function
Uncaught TypeError: t.props.utils.startOfMonth is not a function

**Comment by dmtrKovalenko** [comment] 2019-01-21 15:04
Duplicate of #864

**Closed** 2019-01-21 15:04 UTC
