### ISSUE TITLE
Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in DatePicker

### ISSUE THREAD

**Issue by JMV2112** [dmtrKovalenko/material-ui-pickers#595] opened 2018-08-23 14:55 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.13    |
| material-ui         |    1.5.1     |
| React               |     16.4.2    |
| Browser             |     Chrome    |
| Platform            |    macOS High Sierra 10.13.6     |
| Peer library        |     moment 2.22.2    | 

## Steps to reproduce
1. `import DateTimePicker from 'material-ui-pickers/DateTimePicker'` 
2. I'm running a GatsbyJS project so I run `gatsby develop`

## Expected behavior
The application to run without issues

## Actual behavior
ERROR in ./node_modules/material-ui-pickers/DatePicker/Year.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/DatePicker'
 @ ./node_modules/material-ui-pickers/DatePicker/Year.js 14:60-122
 @ ./node_modules/material-ui-pickers/DatePicker/YearSelection.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePicker.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/DatePicker/Day.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/DatePicker'
 @ ./node_modules/material-ui-pickers/DatePicker/Day.js 14:60-122
 @ ./node_modules/material-ui-pickers/DatePicker/Calendar.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePicker.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/DatePicker/DayWrapper.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/DatePicker'
 @ ./node_modules/material-ui-pickers/DatePicker/DayWrapper.js 14:60-122
 @ ./node_modules/material-ui-pickers/DatePicker/Calendar.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePicker.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/DateTimePicker'
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js 12:60-122
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/_shared/ModalDialog.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/_shared'
 @ ./node_modules/material-ui-pickers/_shared/ModalDialog.js 12:60-122
 @ ./node_modules/material-ui-pickers/wrappers/ModalWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/_shared/DateTextField.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/_shared'
 @ ./node_modules/material-ui-pickers/_shared/DateTextField.js 14:60-122
 @ ./node_modules/material-ui-pickers/wrappers/ModalWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/_shared/MaskedInput.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/_shared'
 @ ./node_modules/material-ui-pickers/_shared/MaskedInput.js 14:60-122
 @ ./node_modules/material-ui-pickers/_shared/DateTextField.js
 @ ./node_modules/material-ui-pickers/wrappers/ModalWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/_shared/PickerToolbar.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/_shared'
 @ ./node_modules/material-ui-pickers/_shared/PickerToolbar.js 12:60-122
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerHeader.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePicker.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/_shared/ToolbarButton.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/_shared'
 @ ./node_modules/material-ui-pickers/_shared/ToolbarButton.js 12:60-122
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerHeader.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePicker.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

ERROR in ./node_modules/material-ui-pickers/wrappers/ModalWrapper.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/.../node_modules/material-ui-pickers/wrappers'
 @ ./node_modules/material-ui-pickers/wrappers/ModalWrapper.js 14:60-122
 @ ./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerWrapper.js
 @ ./node_modules/material-ui-pickers/DateTimePicker/index.js
 @ ./src/components/inquireService.js
 @ ./src/components/footer.js
 @ ./src/components/layout.js
 @ ./src/pages/about.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.

## Live example
https://codesandbox.io/s/9q22938ol4

**Comment by dmtrKovalenko** [comment] 2018-08-23 14:57
Duplicate of #590

**Closed by dmtrKovalenko** 2018-08-23 14:57 UTC
