### ISSUE TITLE
AM / PM change is not working in customization example. Always shows AM after selection.

### ISSUE THREAD

**Issue by moorthi07** [dmtrKovalenko/material-ui-pickers#834] opened 2019-01-05 03:38 UTC
In the **customization example** at material-ui-pickers : https://material-ui-pickers.firebaseapp.com/api/datetimepicker
 
AM / PM  selection is not working . Always shows AM after selection.

 <div className="picker">
          <DateTimePicker
            keyboard
            label="Keyboard with error handler"
            onError={console.log}
            minDate={new Date('2018-01-01T00:00')}
            value={selectedDate}
            onChange={this.handleDateChange}
            **format="yyyy/MM/dd hh:mm A"**
            disableOpenOnEnter

**Comment by moorthi07** [comment] 2019-01-05 19:43
Not mask, In my code , I don't use mask.  But I'm using date-fns. 
Not sure if it works with moment. 
Also this dates are totally different in Mac - Safari browser  where as  Chrome , Firefox and Edge all show one date.

**Comment by dmtrKovalenko** [comment] 2019-01-05 19:53
I see that date is changed in the near picker that means onChange was fired and new date applied

**Comment by moorthi07** [comment] 2019-01-05 19:59
Yes. It is a display problem on the text field. But in Safari - it results in 'minus 1 day'.  Date is applied and you get the right value in the console log - **but not showing right in the display.** Also it only logs  in a very long date format, not in the format we set up in the format attribute.

**Comment by dmtrKovalenko** [comment] 2019-01-05 21:08
@moorthi07 found the reason. It's actually related to the token 'A' in the format string. I didn't fully understand whats wrong with that, but seems like it is deprecated and match the symbok 'A' now. `format="yyyy/MM/dd hh:mm a"` totally fix issue. https://codesandbox.io/s/rjqvlkqp54

Should be fixed here -> https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/docs/src/Pages/Components/DateTimePicker/CustomDateTimePicker.example.jsx#L59

**Comment by moorthi07** [comment] 2019-01-05 22:20
Great catch. Here are some updates. 'A' for AM/PM works find with **moment**.js. But for the **date**-fns - 'A' doesn't work, that needs a 'a'.

Well, but both don't work on Safari browser. I'll create another issue on that. By the way did you check this on Safari

**Closed** 2019-01-24 09:52 UTC
Labels: docs, needs work

**Comment by HenriqueDerosa** [comment] 2021-02-01 19:33
Why am/pm doesn't work with date-fns. Is there any workaround ?
In my case, pm is selected by default, and I can't change it.

**Comment by oliviertassinari** [comment] 2021-02-14 01:50
@HenriqueDerosa Do you have a reproduction with v5?
