### ISSUE TITLE
Date Picker and DateTime Picker broken in IE11

### ISSUE THREAD

**Issue by andokai** [dmtrKovalenko/material-ui-pickers#175] opened 2018-01-11 20:42 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-beta.12 |
| material-ui         | 1.0.0-beta.27 |
| React               | 16.2.0 |
| Browser             | IE11 |
| Platform            | Windows 10 |

## Steps to reproduce
1. Visit https://material-ui-pic.firebaseapp.com/
2. Try to open a date picker or datetime picker

## Expected behavior

To see the picker
## Actual behavior

Screen whites out with "Object doesn't support property or method 'from'" in the console
## Live example
https://material-ui-pic.firebaseapp.com/

**Comment by cherniavskii** [comment] 2018-01-11 20:57
Duplicate of #94

**Closed by cherniavskii** 2018-01-11 20:57 UTC

**Comment by andokai** [comment] 2018-01-11 21:02
Whoops, sorry!
