### ISSUE TITLE
minDate prop in not working.

### ISSUE THREAD

**Issue by omerquyyum** [dmtrKovalenko/material-ui-pickers#76] opened 2017-11-24 14:07 UTC
Warning: React does not recognize the `minDate` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mindate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by dmtrKovalenko** [comment] 2017-11-24 14:28
Please provide the code, you are using

**Comment by dmtrKovalenko** [comment] 2017-11-29 08:20
Closing issue due to no steps to reproduce

**Closed by dmtrKovalenko** 2017-11-29 08:20 UTC
Labels: invalid
