### ISSUE TITLE
onChange method should pass in event

### ISSUE THREAD

**Issue by dawnho** [dmtrKovalenko/material-ui-pickers#767] opened 2018-11-15 19:42 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to have access to the event variable in the onChange method (and perhaps some other ones too)
I want to stop the propagation of the event when the picker is clicked. Right now, I have my picker situated in an expand accordion, which closes everytime I select a date.

**Describe the solution you'd like**
Make the event available in 'onChange' method.

**Describe alternatives you've considered**
Adding stop propagation to the onClick method, but that ends up disabling the calendar

**Comment by dmtrKovalenko** [comment] 2018-11-15 19:44
We can’t

**Comment by dmtrKovalenko** [comment] 2018-11-15 19:44
Duplicate of #

**Closed by dmtrKovalenko** 2018-11-15 19:44 UTC

**Comment by iksent** [comment] 2019-12-18 14:29
I have fixed it by adding another container-`div` with `onClick`-handler to stop propagation of event.

```
<div onClick={(event) => event.stopPropagation()}>
  <DatePicker
    variant="inline"
    ...
  </DatePicker>
</div>
```
