### ISSUE TITLE
Style DateTimePicker date and time display

### ISSUE THREAD

**Issue by phiilu** [dmtrKovalenko/material-ui-pickers#97] opened 2017-12-12 09:24 UTC
Is it possible to set some styles to the date and time representation?

<img width="320" alt="screen shot 2017-12-12 at 10 18 20" src="https://user-images.githubusercontent.com/8149519/33876714-8f3656c2-df26-11e7-8d9e-72da57024288.png">

As you can see there is no margin between the date and the time.

**Comment by dmtrKovalenko** [comment] 2017-12-13 09:34
Duplicate of #51

**Closed by dmtrKovalenko** 2017-12-13 09:34 UTC
Labels: duplicate
