### ISSUE TITLE
wrong day numbers

### ISSUE THREAD

**Issue by Mario-Eis** [dmtrKovalenko/material-ui-pickers#427] opened 2018-05-21 18:55 UTC
## Environment

    "@material-ui/core": "1.0.0-rc.1",
    "material-ui-pickers": "1.0.0-rc.9",

## Actual behavior

![issue](https://user-images.githubusercontent.com/17924929/40324021-7b2fe76c-5d37-11e8-895c-defc8efca011.png)

![issue2](https://user-images.githubusercontent.com/17924929/40324319-7071b76e-5d38-11e8-887e-b7b8c40594be.png)

The numbers are starting with 1 on the first of january and are rising to 365 in december.

## Steps to reproduce
I have absolutely no idea how to reproduce it. This seems to happen since around @material/core 1.0.0-rc.  Some of the builds SEEM very rarely to be working though and the numbers of the days are correct again. Maybe an issue with semantic versioning? I tried to fix all relevant versions in my package.json. But no luck. **This is just a guess!** It's happening very often. And maybe the working builds are just some cache issues.
I'm on it for several hours now. But I really am out of ideas how to fix it...

A downgrade to 

    "material-ui": "^1.0.0-beta.47",
    "material-ui-pickers": "1.0.0-rc.7",

seems to fix the issue permanently.

**Comment by cherniavskii** [comment] 2018-05-21 19:35
Duplicate of #424

**Closed by cherniavskii** 2018-05-21 19:35 UTC

**Comment by Mario-Eis** [comment] 2018-05-21 19:51
You are so right! Sorry for the duplicate. The issue was indeed semantic versioning of "date-fns": "^2.0.0-alpha.7"
