### ISSUE TITLE
Floating label issue

### ISSUE THREAD

**Issue by ritesh-malav** [dmtrKovalenko/material-ui-pickers#467] opened 2018-06-13 04:24 UTC
I have been using this library in react material ui but there is something strange behaviour about the floating label in it. Whenever you click in the text field then the label goes up but upon selecting the date and the clearing it to null or "" the label does not come down. Is this already an issue or it's something that i am only facing ?

**Comment by LironGetJones** [comment] 2018-06-13 07:44
maybe duplicate of #451

**Closed** 2018-06-13 08:37 UTC
Labels: duplicate
