### ISSUE TITLE
Date Picker does not work in IE11

### ISSUE THREAD

**Issue by aansel** [dmtrKovalenko/material-ui-pickers#189] opened 2018-01-23 07:48 UTC
When you click on the date picker on IE11 you get a blank page. You can reproduce the issue on the demo website here: https://material-ui-pic.firebaseapp.com/
Time picker seems to work fine.

**Comment by cherniavskii** [comment] 2018-01-23 08:03
Please follow our issue template when reporting bugs

**Comment by dmtrKovalenko** [comment] 2018-01-23 08:23
Duplicate of #94

**Closed by dmtrKovalenko** 2018-01-23 08:23 UTC
